### PR TITLE
chore: Add SSEC Team to software authors

### PR DESCRIPTION
**Pull request by lsetiawan**
This pull request includes updates to the `CITATION.cff` file to add new authors to the citation information for the software. The most important changes include the addition of four new authors along with their ORCID identifiers.

Updates to `CITATION.cff`:

* Added new author "Landung Setiawan" with ORCID `https://orcid.org/0000-0002-1624-2667`.
* Added new author "Ayush Nag" with ORCID `https://orcid.org/0009-0008-1790-597X`.
* Added new author "Madeline Gordon" with ORCID `https://orcid.org/0009-0003-6220-7218`.

### CODE REVIEW

**Comment by lsetiawan** [comment]
@ayushnag and @madelinegordon please double check your name and how you want to be cited for the software. Thanks!

**Comment by ayushnag** [comment]
@lsetiawan Mine is correct!

**Comment by madelinegordon** [comment]
@lsetiawan Mine is correct as well!

**Review by madelinegordon — APPROVED** [review]

**Review by ayushnag — APPROVED** [review]

**Comment by lsetiawan** [comment]
Yay! Now we all will be authors for this software 😄

**Pull request merged**
