### PR TITLE
feat: Add 'add_leaf' and 'remove_leaf' methods

### LINKED ISSUE #20: feat: Add 'add_leaf' function so user can add a leaf to the Vector
## Overview

There's an `addLeaf` to the cpp implementation, see https://github.com/Neclow/phylo2vec_dev/blob/320812ac9396a9a5d17bca3047ee39c8eb22f95e/cpp/utils/vector.cpp#L21-L57. We need to add this to the rust implementation.

### LINKED ISSUE #21: feat: Add 'remove_leaf' function for Vector
## Overview

There's a `removeLeaf` function implementation in cpp that we need to port to Rust: https://github.com/Neclow/phylo2vec_dev/blob/320812ac9396a9a5d17bca3047ee39c8eb22f95e/cpp/utils/vector.cpp#L59-L112

### PR DESCRIPTION
**Pull request by ayushnag**
This pull request introduces several new features and improvements to the `TreeVec` struct in the `phylo2vec` library. The changes include new methods for manipulating the tree structure, additional documentation, and new tests to ensure functionality.

### Enhancements to `TreeVec` struct:

* [`phylo2vec/src/tree_vec/mod.rs`](diffhunk://#diff-93651a78de451eb71d57f7b5f50421603e29b7607e886401e3e60bc90d8c8de9R46-R168): Added new methods `add_leaf`, `remove_leaf`, and `from_sample` to the `TreeVec` struct, allowing for dynamic manipulation of the tree structure.
* [`phylo2vec/src/tree_vec/mod.rs`](diffhunk://#diff-93651a78de451eb71d57f7b5f50421603e29b7607e886401e3e60bc90d8c8de9R46-R168): Implemented the `to_newick` method to convert the tree to Newick format and updated the `get_ancestry` method to return an `Ancestry` type.

### Documentation improvements:

* [`phylo2vec/src/tree_vec/mod.rs`](diffhunk://#diff-93651a78de451eb71d57f7b5f50421603e29b7607e886401e3e60bc90d8c8de9R20-R30): Added detailed documentation for the `TreeVec` struct and its methods, including `new`, `from_sample`, `to_newick`, `get_ancestry`, `add_leaf`, and `remove_leaf`. [[1]](diffhunk://#diff-93651a78de451eb71d57f7b5f50421603e29b7607e886401e3e60bc90d8c8de9R20-R30) [[2]](diffhunk://#diff-93651a78de451eb71d57f7b5f50421603e29b7607e886401e3e60bc90d8c8de9R46-R168)

### Test additions:

* [`phylo2vec/src/tree_vec/mod.rs`](diffhunk://#diff-93651a78de451eb71d57f7b5f50421603e29b7607e886401e3e60bc90d8c8de9R194-R196): Added new tests for creating trees from samples, converting trees to Newick format, retrieving ancestry matrices, and adding/removing leaves from the tree. [[1]](diffhunk://#diff-93651a78de451eb71d57f7b5f50421603e29b7607e886401e3e60bc90d8c8de9R194-R196) [[2]](diffhunk://#diff-93651a78de451eb71d57f7b5f50421603e29b7607e886401e3e60bc90d8c8de9R208-R210) [[3]](diffhunk://#diff-93651a78de451eb71d57f7b5f50421603e29b7607e886401e3e60bc90d8c8de9R221-R223) [[4]](diffhunk://#diff-93651a78de451eb71d57f7b5f50421603e29b7607e886401e3e60bc90d8c8de9L108-R278)

### Utility functions:

* [`phylo2vec/src/tree_vec/ops/vector.rs`](diffhunk://#diff-121649f3c42bdce021f4118590bc2832ab387ba3998f82270cd2bfc6aaa75a4bR191-R299): Added utility functions `find_coords_of_first_leaf`, `order_cherries`, `order_cherries_no_parents`, and `build_vector` to support the new `TreeVec` methods.

### Code refactoring:

* [`phylo2vec/src/tree_vec/ops/vector.rs`](diffhunk://#diff-121649f3c42bdce021f4118590bc2832ab387ba3998f82270cd2bfc6aaa75a4bL124-R143): Refactored the `get_ancestry` function to use `usize::MAX` instead of `-1` for uninitialized parent values, improving type safety and clarity.

These changes collectively enhance the functionality, documentation, and test coverage of the `TreeVec` struct, making the library more robust and easier to use.

## TODOs

- [x] Add docs
- [x] Tests added
- [x] Tests passing

## Related Issues

- [x] Closes #20
- [x] Closes #21

### CODE REVIEW

**Comment by lsetiawan** [comment]
@ayushnag I've fixed the bugs to add leaf method. looks like now there's a merge conflict. Could you please resolve this? Thanks!

**Comment by lsetiawan** [comment]
@ayushnag I went ahead and fixed the merge conflicts, now the only thing failing is the remove_leaf, which I think need to be updated.

**Comment by lsetiawan** [comment]
@ayushnag Thanks for the initial codebase, I was able to quickly update the code and make it work. 😄 I think this is good now.

**Review by lsetiawan — APPROVED** [review]

**Comment by ayushnag** [comment]
Thanks @lsetiawan!

**Pull request merged**
